#!/bin/bash
source /opt/usersync/app.env
rootdir="/opt/ldapsync"
binpath="/opt/ldapsync/bin"
logpath=$rootdir"/logs"
dt=`date "+%Y_%b_%d_%T"`
logile="ldapsync.log"
site_mvpcc=1
#corportae LDAP details
CorporateLDAP=`echo $CORPORATE_LDAP_URL| cut -d ":" -f 1`
#Regional LDAP details
RegionalLDAP=`echo $CHAMBER_0_LDAP_URL| cut -d ":" -f 1`
REGIONAL_SITE=`hostname | cut -c 1-4` 
RegionalLDAPPW=`openssl passwd -1 -salt $REGIONAL_SITE $LDAP_PW_BASE |cut -d "$" -f4`

#####CC LDAP Details
CCLDAP=""
CCLDAPPW=""
if [[ "$site_mvpcc" != 0 ]];then
    CCLDAP=`echo $CC_CHAMBER_0_LDAP_URL| cut -d ":" -f 1`
    CC_SITE="${CC_ENV_PREFIX}00"
    CCLDAPPW=`openssl passwd -1 -salt $CC_SITE $LDAP_PW_BASE |cut -d "$" -f4`
fi


#Other Details
VCAD_BASEDN="ou=vcad,ou=services,o=cadence.com"
CORPEMP_BASEDN="ou=people,o=cadence.com"
CorporateLDAPUser="uid=ldapbind,ou=Groups,o=cadence.com"
RegionalLDAPUser="cn=directory manager"

CorpVCADLDIF="CorpVCAD.ldif"
RegVCADLDIF="RegVCAD.ldif"
OutVCADLDIF="OutVCAD.ldif"

CorpEMPLDIF="CorpEMP.ldif"
RegEMPLDIF="RegEMP.ldif"
OutEmpLDIF="OutEmp.ldif"


CCEMPLDIF="CCEMP.ldif"
CCVCADLDIF="CCVCAD.ldif"
CCOutVCADLDIF="CCOutVCAD.ldif"
CCOutEmpLDIF="CCOutEmp.ldif"



EmpAttrs="objectclass mail sn cn loginShell givenName homeDirectory gecos gidNumber userPassword uidNumber uid displayName o vcadaccess" 
#ADMIN="mana@cadence.com arul@cadence.com nishant@cadence.com"


sping() {

                OT=`/usr/bin/ping -c1 $1 > /dev/null; echo $?`
                if [[ "$OT" != 0 ]];then
                                echo "$dt : ERROR Server $1 not reachable.... Alerting & Exit !!!" >> $logpath/$logile
                                echo ""|mail -s "Failed: LDAP SYNC Server not reachable : $1 : Exiting !!!" $ADMIN
                                exit 101
                else
                                echo "$dt : Success Server $1 is reacheable...." >> $logpath/$logile
                fi
}

createLDIF() {
                local ldapHost=$1
                local ldapUser=$2
                local ldapPw=$3
                local basedn=$4
                local ldifFile=$5
                local vcadaccess=$6
                echo "ldapHost=$ldapHost ,  ldapUser=$ldapUser ,  basedn=$basedn,  ldifFile=$ldifFile , vcadaccess=$vcadaccess"

                echo "$dt : Generating source server cooperate LDIF !!!" >> $logpath/$logile
                if [[ $vcadaccess ]] ; then
                    echo "Inside vcadaccess "
                    /usr/bin/ldapsearch -x -o ldif-wrap=no -h "$ldapHost" -D "$ldapUser" -b "$basedn" -w "$ldapPw"  "VCADaccess=*" -LLL $EmpAttrs | grep -iv "objectclass: cdsAccess" | grep -iv "objectclass: cadencePerson" |grep -iv "objectclass: dspswuser"  > $logpath/tmp1_$ldifFile
                    #sed "s/cdslastPwdchanged:/shadowLastChange:/g" $logpath/tmp1_$ldifFile > $logpath/tmp2_$ldifFile
                    sed "s/gidNumber:.*/gidNumber: 201/g" $logpath/tmp1_$ldifFile >$logpath/$ldifFile
                    rm -rf $logpath/tmp1_$ldifFile 
                else
                    echo "else vcadaccess"
                    /usr/bin/ldapsearch -x -o ldif-wrap=no -h "$ldapHost" -D "$ldapUser" -b "$basedn" -w "$ldapPw" -LLL  |grep -iv "shadowLastChange" > $logpath/$ldifFile
                fi
                if test -f $logpath/$ldifFile; then
                                echo "$dt :LDIF generated ( $ldifFile )with total DNs : `grep "^dn" $logpath/$ldifFile|wc -l`" >> $logpath/$logile
                else
                                echo "$dt : ERROR Failed to generate  LDIFF" >> $logpath/$logile
                                #echo ""|mail -s "Failed to generate Corporate Server VCAD Tree  LDIF : $SourceServer : Exiting !!!" $ADMIN
                                exit 102
                fi

}

diffLDIF() {
                local source=$1
                local destination=$2
                local out=$3
                echo "$dt : Generating DIFF $out LDIF" 
                echo "$dt : Generating DIFF $out LDIF" >> $logpath/$logile
                export _JAVA_OPTIONS=-Xmx4096m
                $binpath/ldif-diff -o $logpath/$out -s $logpath/$destination -t $logpath/$source -e $binpath/system_users.ldif
                unset _JAVA_OPTIONS
                if test -f $logpath/$out; then
                    echo "$dt : DIFF $out LDIF generated with total DNs : `grep "^dn" $logpath/$out|wc -l`" >> $logpath/$logile

                else
                    echo "$dt : ERROR Failed to generate DIFF LDIF" >> $logpath/$logile
                    #echo ""|mail -s "Failed to generate DIFF LDIF for VCAD Sync ... Exiting !!!" $ADMIN
                    exit 105
                fi
}

modify() {
                local difffile=$1
                local ldapHost=$2
                local ldapUser=$3
                local ldapPw=$4
                WC=`grep "^# No differences" $logpath/$difffile|wc -l`
                if  [[ "$WC" == 1 ]];then
                    echo "$dt : No changes found in Source and Target $difffile LDIF ... " >> $logpath/$logile
                    #exit 104
                else
                    echo "$dt : Modifying LDAP Destination Server $ldapHost with `grep "^dn" $logpath/$difffile|wc -l` changes... "
                    echo "$dt : Modifying LDAP Destination Server $ldapHost with `grep "^dn" $logpath/$difffile|wc -l` changes... " >> $logpath/$logile
                    /usr/bin/ldapmodify -c -xh $ldapHost -D "$ldapUser" -w $ldapPw -f $logpath/$difffile > $logpath/ldapmodify.log 2>&1
                    OT_mod=`echo $?`
                    if [[ "$OT_mod" == 0 ]];then
                                    echo "$dt : Modification succesful at Destination Server" >> $logpath/$logile
                                    #cat $logpath/ldapmodify.log|mail -s "LDAP SYNC : `grep '^dn' $logpath/$difffile|wc -l` records updated from $SourceServer to $RegionalLDAP" 
                    else
                                    echo "$dt : Modification failed with errors please check $logpath/ldapmodify.log" >> $logpath/$logile
                                    #cat $logpath/ldapmodify.log|mail -s "LDAP SYNC : `grep '^dn' $logpath/DIFF.ldif|wc -l` records updated from $SourceServer to $DestServer" $ADMIN
                                    #echo ""|mail -s "Failed: VCAD LDAP SYNC Modification with errors please check $logpath/ldapmodify-$dt.log" $ADMIN
                    fi
                fi
}

rotate() {
                echo "$dt : Rotating files to $dt timestamp" >> $logpath/$logile
                rm $logpath/$CorpVCADLDIF $logpath/$CorpEMPLDIF 
                rm $logpath/$RegVCADLDIF $logpath/$RegEMPLDIF
                mv $logpath/$OutVCADLDIF $logpath/$dt-$OutVCADLDIF
                mv $logpath/$OutEmpLDIF $logpath/$dt-$OutEmpLDIF
                if [[ "$site_mvpcc" != 0 ]];then
                    rm $logpath/$CCVCADLDIF $logpath/$CCEMPLDIF
                    mv $logpath/$CCOutVCADLDIF $logpath/$dt-$CCOutVCADLDIF
                    mv $logpath/$CCOutEmpLDIF $logpath/$dt-$CCOutEmpLDIF
                fi
                            
                echo "$dt : Rotation completed & script completed successfully @ `date`" >> $logpath/$logile
}


if [[ `pgrep -f "/bin/bash $0"` != "$$" ]]; then
        echo "Another instance of shell already exist! Exiting"
        exit
fi

dts=`date "+%Y_%b_%d_%T"`
startDate=`date "+%s"`
echo "Starting time $dts"

#Create VCAD Tree LDIF from Cooperate LDAP
createLDIF "$CorporateLDAP" "$CorporateLDAPUser" "$CORPORATE_LDAP_BIND_PW" "$VCAD_BASEDN" "$CorpVCADLDIF"
#Create VCAD Tree LDIF from Regional LDAP
createLDIF "$RegionalLDAP" "$RegionalLDAPUser" "$RegionalLDAPPW" "$VCAD_BASEDN" "$RegVCADLDIF"
#Create Employee Tree LDIF from Cooperate LDAP
createLDIF "$CorporateLDAP" "$CorporateLDAPUser" "$CORPORATE_LDAP_BIND_PW" "$CORPEMP_BASEDN" "$CorpEMPLDIF" "vcadaccess"
#Create Employee Tree LDIF from Regional LDAP
createLDIF "$RegionalLDAP" "$RegionalLDAPUser" "$RegionalLDAPPW" "$CORPEMP_BASEDN" "$RegEMPLDIF"

######Find Difference of Regional LDAP
diffLDIF "$CorpVCADLDIF" "$RegVCADLDIF" "$OutVCADLDIF"
diffLDIF "$CorpEMPLDIF" "$RegEMPLDIF" "$OutEmpLDIF"

modify $OutVCADLDIF "$RegionalLDAP" "$RegionalLDAPUser" "$RegionalLDAPPW"
modify $OutEmpLDIF "$RegionalLDAP" "$RegionalLDAPUser" "$RegionalLDAPPW"

if [[ "$site_mvpcc" != 0 ]];then
    echo "Inside CC LDAP Processing"
    #Create VCAD Tree LDIF from CC LDAP
    createLDIF "$CCLDAP" "$RegionalLDAPUser" "$CCLDAPPW" "$VCAD_BASEDN" "$CCVCADLDIF"
    #Create Employee Tree LDIF from CC LDAP
    createLDIF "$CCLDAP" "$RegionalLDAPUser" "$CCLDAPPW" "$CORPEMP_BASEDN" "$CCEMPLDIF"
    ######Find Difference of CC LDAP
    diffLDIF "$CorpVCADLDIF" "$CCVCADLDIF" "$CCOutVCADLDIF"
    diffLDIF "$CorpEMPLDIF" "$CCEMPLDIF" "$CCOutEmpLDIF"
    modify $CCOutVCADLDIF "$CCLDAP" "$RegionalLDAPUser" "$CCLDAPPW"
    modify $CCOutEmpLDIF  "$CCLDAP" "$RegionalLDAPUser" "$CCLDAPPW"
fi

#Rotate Logs
rotate

#Delete logs Files older than 1 day
find $logpath/*.ldif -maxdepth 1 -mtime +0 -type f -exec rm {} +

dte=`date "+%Y_%b_%d_%T"`
echo "End time $dte"
endDate=`date "+%s"`
DIFF=$(($endDate-$startDate))
echo "Duration: $(($DIFF / 3600 )) hours $((($DIFF % 3600) / 60)) minutes $(($DIFF % 60)) seconds"


